networks:
  internal:

services:
  api:
    image: $apiImage

    stop_grace_period: 30s

    cpu_count: 1
    cpu_shares: 1024
    mem_limit: 256m

    restart: unless-stopped

    networks:
      internal:

    environment:
      - OPENAI_API_KEY=${openaiApiKey}
      - DEBUG=${apiDebug:-}

    logging:
      driver: json-file
      options:
        max-size: '10m'
        max-file: '2'

  bot:
    image: $botImage

    stop_grace_period: 30s

    cpu_count: 1
    cpu_shares: 1024
    mem_limit: 256m

    restart: unless-stopped

    networks:
      internal:

    depends_on:
      - api

    environment:
      - DEBUG=${botDebug:-}
      - BOT_TOKEN=${botToken}
      - CHAT_API_BASE_URL=${appId}-api

    logging:
      driver: json-file
      options:
        max-size: '10m'
        max-file: '2'
